#!/bin/bash

echo "📧 GameStack Email Configuration Setup"
echo "======================================"
echo ""
echo "This script will help you configure Gmail for OTP emails."
echo ""
echo "Prerequisites:"
echo "1. Gmail account with 2-Step Verification enabled"
echo "2. Gmail App Password (16 characters)"
echo ""
echo "To get Gmail App Password:"
echo "1. Go to: https://myaccount.google.com/security"
echo "2. Enable 2-Step Verification (if not already enabled)"
echo "3. Go to 'App passwords' section"
echo "4. Create new app password for 'Mail'"
echo "5. Copy the 16-character password"
echo ""
read -p "Enter your Gmail address: " email
read -sp "Enter your Gmail App Password (16 chars): " password
echo ""
echo ""
echo "Setting environment variables for current session..."
export MAIL_USERNAME="$email"
export MAIL_PASSWORD="$password"
echo ""
echo "✅ Environment variables set!"
echo ""
echo "To make these permanent, add to your ~/.zshrc or ~/.bashrc:"
echo "export MAIL_USERNAME=\"$email\""
echo "export MAIL_PASSWORD=\"$password\""
echo ""
echo "Now restart the backend to apply changes."
